### ISSUE TITLE
Kubernetes documentation references deprecated, unmaintained repo

### ISSUE THREAD

**Issue by stenwt** [games-on-whales/gow#102]
The k8s-at-home repo has been deprecated and archived, it should not be referenced in the documentation. 

https://github.com/k8s-at-home/charts/issues/1761

**Comment by zb140** [comment]
I'm inclined to update the docs to clearly call out that k8s-at-home is deprecated, but otherwise leave things as-is for now.  The k8s support is something that I think many of us use much, so I wouldn't know what to replace it with, and I hate to tear it out completely if it might be able to give someone a head start. At the same time, we definitely should make the deprecation clear so people won't spend time trying to implement it without realizing.

cc @angelnu : do you have any advice?

**Comment by angelnu** [comment]
I moved the helm chart to my personal repository as other members of the community did: https://github.com/angelnu/helm-charts/tree/main/charts/apps/games-on-whales

So an easy fix is to just update the documentation.

On the other side the helm chart would welcome some additional work to make things easier as it is currently quite basic. Up to the community if anyone wants to to extend it -  PRs are always welcome.
