### ISSUE TITLE
Fatal error received in: "video_driver_init_internal()"

### ISSUE THREAD

**Issue by TenyamaGain** [games-on-whales/gow#169]
I'm attempting to get this working -- that said, one note should be made first off -- I have to run docker as root. It's a long and complicated story, but yeah. I'm also on NixOS.

So, I did the basic commands, and then it starts doing what looks like generating smth (counting from 0% to 100%), then at the bottom, says this.
```
retroarch-1  | Authorization required, but no authorization protocol specified
retroarch-1  | 
retroarch-1  | Authorization required, but no authorization protocol specified
retroarch-1  | 
retroarch-1  | amdgpu_device_initialize: amdgpu_query_info(ACCEL_WORKING) failed (-13)
retroarch-1  | amdgpu: amdgpu_device_initialize failed.
retroarch-1  | Fatal error received in: "video_driver_init_internal()"
retroarch-1 exited with code 1
```
And after a moment or two after this,

```
sunshine-1   | [2024-02-09 01:48:27] FATAL: /opt/gow/wait-x11: Gave up waiting for X server :0
sunshine-1 exited with code 11
```

Furthermore, after I run it again with that user,
```
[user@user-NAS:/aeternae/data_servers/gow]$ bash ./run-gow --app retroarch up
Running docker compose...
[+] Running 2/0
 ✔ Container gow-retroarch-1  Created                                                                                                                            0.0s 
 ✔ Container gow-sunshine-1   Created                                                                                                                            0.0s 
Attaching to retroarch-1, sunshine-1
retroarch-1  | [2024-02-09 01:42:55] 
retroarch-1  | [2024-02-09 01:42:55] [ /etc/cont-init.d/10-setup_user.sh: executing... ]
retroarch-1  | [2024-02-09 01:42:55] **** Configure default user ****
retroarch-1  | [2024-02-09 01:42:55] Setting default user uid=1000(retro) gid=1000(retro)
retroarch-1  | userdel: retro mail spool (/var/mail/retro) not found
retroarch-1  | userdel: error removing directory /home/retro
sunshine-1   | [2024-02-09 01:42:56] 
sunshine-1   | [2024-02-09 01:42:56] [ /etc/cont-init.d/10-setup_user.sh: executing... ]
sunshine-1   | [2024-02-09 01:42:56] **** Configure default user ****
sunshine-1   | [2024-02-09 01:42:56] Setting default user uid=1000(retro) gid=1000(retro)
sunshine-1   | userdel: retro mail spool (/var/mail/retro) not found
sunshine-1   | userdel: error removing directory /home/retro
retroarch-1 exited with code 12
sunshine-1 exited with code 12
```

Anybody able to help, by chance?

**Comment by ABeltramo** [comment]
> Authorization required, but no authorization protocol specified
Are you trying to share the host Xorg session? You might have access control enabled; you either need to mount the Xorg cookie (usually under `~/.Xauthority`) or you can disable access control using `xhost +`

> Fatal error received in: "video_driver_init_internal()"
This seems a different issue; could it be that you have the proprietary AMD driver installed? Can you revert back to use the open source Mesa drivers?

On a different note, the GOW script is getting rusty and unmaintained; I'm working on Wolf <https://github.com/games-on-whales/wolf> as a replacement for this stack, would you be interested in trying it out? We are also working on a nix package instead of using Docker to bundle Wolf if that's something that might be of interest for you <https://github.com/games-on-whales/wolf/pull/53>
