### ISSUE TITLE
failed to create symbolic (nvidia)

### ISSUE THREAD

**Issue by Gylfkxjyjdll** [games-on-whales/gow#179]
I installed GoW with the quickstart: https://games-on-whales.github.io/wolf/stable/user/quickstart.html

Everything worked so far, but asap i start up gow, I receive this error:

```
wolf-1  | [2024-07-16 16:11:35] [nvidia] Add Vulkan ICD
wolf-1  | [2024-07-16 16:11:35] [nvidia] Add EGL external platform
wolf-1  | [2024-07-16 16:11:35] [nvidia] Add egl-vendor
wolf-1  | [2024-07-16 16:11:35] [nvidia] Add gbm backend
wolf-1  | [2024-07-16 16:11:35] Nvidia driver detected, assuming it's using the nvidia driver volume
wolf-1  | /sbin/ldconfig.real: /usr/local/lib/liblibgstwaylanddisplay.so.0.2 is not a symbolic link
wolf-1  | 
wolf-1  | [2024-07-16 16:11:35] Creating symlink to nvidia-drm_gbm.so
wolf-1  | ln: failed to create symbolic link '/usr/lib/x86_64-linux-gnu/gbm/nvidia-drm_gbm.so': File exists
```

Hardware:
Nvidia 4060rtx with Debian 12 headless with Dummystick

**Comment by ABeltramo** [comment]
> wolf-1  | [2024-07-16 16:11:35] Creating symlink to nvidia-drm_gbm.so
> wolf-1  | ln: failed to create symbolic link '/usr/lib/x86_64-linux-gnu/gbm/nvidia-drm_gbm.so': File exists`


The error here indicates that the driver files are already there; this is most likely because you've set the `nvidia` Docker runtime to be the default, so it'll mount those libraries from the host.  
Unfortunately, the Nvidia container runtime toolkit is not yet able to add all the required libraries (there's a separate PR and upstream work going on)..

In the meantime, you have to avoid using the Nvidia runtime; can you try using `--runtime=runc`? I'll have to check what's the exact sintax, I'm on my phone right now.

**Comment by ABeltramo** [comment]
I've pushed a fix for this weird behaviour, you can check it out by updating Wolf using
```
docker pull ghcr.io/games-on-whales/wolf:stable
```
and try running it again. Feel free to re-open if it doesn't work for you.

**Comment by Gylfkxjyjdll** [comment]
Works. Thanks!
