### ISSUE TITLE
Switch from X11 to Wayland

### ISSUE THREAD

**Issue by iMonZ** [games-on-whales/gow#46]
Switching from the X11 Display Server to the Wayland Display Server (with Pipewire)

**Comment by ABeltramo** [comment]
Can we open up a discussion about what are the pros/cons of doing this switch? Why would you like to see GOW running on Wayland? What's the issue with X11?
AFAIK Sunshine supports it but this will need to be properly checked.

**Comment by iMonZ** [comment]
Since X11 will be deprecated and most work of most tools will be focused on Wayland.
Also features like higher resolutions or HDR are only good implemented on Wayland.
So X11 will be a thing of the past

**Comment by a-priestley** [comment]
Sorry to resurrect, but I want to second this idea at least as an option. wayland is a much cleaner implementation than x11, specifically if you are not actually interested in running a gui. If your goal is simply to connect to a game instance running over sunshine, it should be super clean to run it as a single compositor window, and then tear it down again when you're done.

**Comment by ABeltramo** [comment]
A year as passed since this was originally posted; lots of things are currently changing under the hood!

I'm [implementing an alternative to Sunshine](https://github.com/games-on-whales/wolf) that's going to be tailored down for our needs. The main objectives are the followings:

- Multi user: a single instance must be able to serve different users.
  - Each user will have a separate (virtual) desktop with HW acceleration and proper input separation (pads, keyboards, mouse).
  - Optionally (not sure how feasible it is) keep also the ability to share sessions between multiple users (co-op games).
- Linux based, Docker first. There's no need to replace Sunshine.

I feel that Wayland will be the right way forward but I haven't properly dig into this; any help or suggestion here is more than welcome!  

I don't know if we can use something like Sway or if we have to create a custom Wayland compositor tailored for our needs; either way, we'll get there!!

**Comment by a-priestley** [comment]
This is fantastic news. Something to point out: Multi-user session sharing is indeed possible, as demonstrated by Steam Remote Play Together

**Comment by ABeltramo** [comment]
Sunshine supports that too, I would like to support both options though (if possible)!

**Comment by a-priestley** [comment]
Is there something specific to running inside a container that makes multi-user session tricky to pull off? You might be able to use a reverse proxy to dynamically map ports to connected clients

**Comment by ABeltramo** [comment]
The problem is not running inside Docker, and there's no problem in sharing the same screen/session with multiple users like Steam and Sunshine do.  
The problem is most likely how to create separate screens on demand that are still HW accelerated with no overlapping in video/audio/inputs.    

The ultimate goal is to allow multiple users to effectively share a single machine in order to play different games.

I believe it's tecnically possible but I don't think there's anything like that out there. All desktop streaming software are focused on single desktop/session sharing OR multiple remote virtual session (with no HW acceleration or at least not capable of playing games effectively).

**Comment by a-priestley** [comment]
I think I understand what you mean. It does pose several challenges. Do you create a sound server per user or each user would get their own sink on the same server? etc.
The simplest solution I think might be a container per user, but that would probably create a ton of unnecessary overhead for the host.
It would be one hell of an accomplishment either way

**Comment by ABeltramo** [comment]
We've ended up writing our micro custom Wayland comp in [Wolf](https://github.com/games-on-whales/wolf)
