### ISSUE TITLE
Set the locale for the steam container

### ISSUE THREAD

**Issue by Sparticuz** [games-on-whales/gow#71]
```gow-steam-1     | WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work. ```

![image](https://user-images.githubusercontent.com/161913/186675682-85de0149-34a6-4f69-8f20-627a51292498.png)

**Comment by zb140** [comment]
Looks like we need to install the `locales` package and run `locale-gen en_US.UTF-8` as part of the build process.

**Comment by zb140** [comment]
It really seems like this should be easy to fix, but for some reason, it isn't.  I can fix it with the steps I mentioned above in a container that already exists, but when I try to add those steps to the container build, it doesn't seem to consistently fix the problem.  So, this bug is still open. But I haven't given up yet :grin:

**Comment by ABeltramo** [comment]
No longer an issue on Wolf
