### ISSUE TITLE
Add wine image for launching Win-based games

### ISSUE THREAD

**Issue by QuaiGoner** [games-on-whales/gow#88]
Reference - https://hub.docker.com/r/scottyhardy/docker-wine/

**Comment by zb140** [comment]
At a super-quick glance, this image should be fairly easy to make work with GOW, since it already expects a running Xorg server external to itself.  In theory, creating a `compose/wine.yml` that sets up the `DISPLAY` env var, as well as a volume mount for the Xorg socket should be enough. Pulse may take a little extra effort but probably not much.

**Comment by ABeltramo** [comment]
It has been some time that we can run Proton games in our Steam image, closing this.
